FLAGS = -std=c99 -Wall -O -L/home/wallace/workSPACE/gitHUB/SourceCODE/tools/textColor -I/home/wallace/workSPACE/gitHUB/SourceCODE/tools/textColor/include


linklist_ext: linklist_ext.c
	@gcc linklist_ext.c -o linklist_ext -lcolor  $(FLAGS)

.PHONY: clean

clean:
	@rm linklist_ext