FLAGS = -std=c99 -Wall -O -L/home/wallace/workSPACE/gitHUB/SourceCODE/tools/textColor -I/home/wallace/workSPACE/gitHUB/SourceCODE/tools/textColor/include


test: test.c
	@gcc test.c -o test -lcolor  $(FLAGS)

.PHONY: clean

clean:
	@rm test
